"""Parity gates: run the VENDORED models in the new unified env against reference outputs
generated by scripts/make_reference_outputs.py in the original validated envs.

Gates (from the plan):
  Retinexformer  uint8 PSNR >= 50 dB   (fp16 cross-torch-version headroom)
  lightSR x2     fp32 seed-0 uint8 PSNR >= 55 dB; autocast-vs-fp32 self-check >= 45 dB
  VideoMamba     logits allclose(rtol=1e-3, atol=1e-3) AND argmax equal
  R(2+1)D-18     logits allclose(rtol=1e-4, atol=1e-4) AND argmax equal
"""
import os, sys
import cv2
import numpy as np
import torch
import torch.nn.functional as F

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
ASSETS = f"{ROOT}/tests/assets"
CKPTS = f"{ROOT}/ckpts"
failures = []


def psnr(a, b):
    mse = np.mean((a.astype(np.float64) - b.astype(np.float64)) ** 2)
    return 99.0 if mse < 1e-9 else 10 * np.log10(255.0 ** 2 / mse)


def gate(name, ok, detail):
    print(f"{'PASS' if ok else 'FAIL'}  {name:14s} {detail}", flush=True)
    if not ok:
        failures.append(name)


def bgr_to_x(bgr, dtype):
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    return torch.from_numpy(rgb).cuda().permute(2, 0, 1).unsqueeze(0).to(dtype).div_(255.0)


def x_to_bgr(y):
    out = y[0].clamp(0, 1).mul(255).round().permute(1, 2, 0).to(torch.uint8).cpu().numpy()
    return cv2.cvtColor(out, cv2.COLOR_RGB2BGR)


# ---------------- Retinexformer ----------------
from darkpipe.vendor.retinexformer_arch import RetinexFormer

dark = np.load(f"{ASSETS}/dark_frame.npy")
net = RetinexFormer(in_channels=3, out_channels=3, n_feat=40, stage=1, num_blocks=[1, 2, 2])
net.load_state_dict(torch.load(f"{CKPTS}/NTIRE.pth", map_location="cpu")["params"], strict=True)
net = net.cuda().eval().half()
with torch.inference_mode():
    x = bgr_to_x(dark, torch.float16)
    h, w = x.shape[2:]
    H, W = (h + 3) // 4 * 4, (w + 3) // 4 * 4
    y = net(F.pad(x, (0, W - w, 0, H - h), "reflect"))[:, :, :h, :w]
out = x_to_bgr(y)
p = psnr(out, np.load(f"{ASSETS}/ref_retinexformer.npy"))
gate("retinexformer", p >= 50, f"PSNR {p:.1f} dB (gate 50)")
del net; torch.cuda.empty_cache()

# ---------------- lightSR x2 ----------------
from darkpipe.vendor.mambairv2light_arch import MambaIRv2Light

enh = np.load(f"{ASSETS}/enh_frame.npy")
sr = MambaIRv2Light(upscale=2, in_chans=3, img_size=64, img_range=1.0, embed_dim=48,
                    d_state=8, depths=[5, 5, 5, 5], num_heads=[4, 4, 4, 4], window_size=16,
                    inner_rank=32, num_tokens=64, convffn_kernel_size=5, mlp_ratio=1.0,
                    upsampler="pixelshuffledirect", resi_connection="1conv")
sd = torch.load(f"{CKPTS}/mambairv2_lightSR_x2.pth", map_location="cpu", weights_only=True)
sr.load_state_dict(sd["params"], strict=True)
sr = sr.cuda().eval()


def run_sr(autocast):
    with torch.inference_mode():
        x = bgr_to_x(enh, torch.float32)
        h, w = x.shape[2:]
        ph, pw = (16 - h % 16) % 16, (16 - w % 16) % 16
        if ph or pw:
            x = F.pad(x, (0, pw, 0, ph), "reflect")
        torch.manual_seed(0)
        with torch.autocast("cuda", dtype=torch.float16, enabled=autocast):
            y = sr(x)
        return x_to_bgr(y.float()[:, :, : h * 2, : w * 2])


out32 = run_sr(False)
p = psnr(out32, np.load(f"{ASSETS}/ref_lightsr.npy"))
gate("lightSR-fp32", p >= 55, f"PSNR {p:.1f} dB (gate 55)")
pac = psnr(run_sr(True), out32)
gate("lightSR-ac", pac >= 45, f"autocast-vs-fp32 PSNR {pac:.1f} dB (gate 45)")
# odd-size pad/crop shape test
with torch.inference_mode():
    xo = torch.rand(1, 3, 233, 317, device="cuda")
    torch.manual_seed(0)
    yo = sr(F.pad(xo, (0, (16 - 317 % 16) % 16, 0, (16 - 233 % 16) % 16), "reflect"))
    yo = yo[:, :, :466, :634]
gate("lightSR-shape", tuple(yo.shape) == (1, 3, 466, 634), f"odd-size out {tuple(yo.shape)}")
del sr; torch.cuda.empty_cache()

# ---------------- R(2+1)D-18 ----------------
from torchvision.models.video import r2plus1d_18
import torch.nn as nn

r3d = r2plus1d_18(weights=None); r3d.fc = nn.Linear(r3d.fc.in_features, 11)
r3d.load_state_dict(torch.load(f"{CKPTS}/r2plus1d_arid.pth", map_location="cpu")["model"])
r3d = r3d.cuda().eval().float()
t16 = torch.from_numpy(np.load(f"{ASSETS}/clip16_tensor.npy")).cuda().float()
with torch.inference_mode():
    lo = r3d(t16).cpu().numpy()
ref = np.load(f"{ASSETS}/ref_r3d_logits.npy")
# 1e-3 tolerance: r3d is unmodified torchvision + identical ckpt; residual diff is
# cuDNN conv-algorithm drift between torch 2.1 (reference env) and 2.7 (this env).
ok = np.allclose(lo, ref, rtol=1e-3, atol=1e-3) and lo.argmax() == ref.argmax()
gate("r3d", ok, f"max|d|={np.abs(lo-ref).max():.2e} argmax {lo.argmax()}=={ref.argmax()}")
del r3d; torch.cuda.empty_cache()

# ---------------- VideoMamba-T 32f ----------------
from darkpipe.vendor.videomamba import videomamba_tiny

vm = videomamba_tiny(num_classes=11, num_frames=32, img_size=224)
vm.load_state_dict(torch.load(f"{CKPTS}/videomamba_t_arid_32f.pth", map_location="cpu")["model"])
vm = vm.cuda().eval().float()
t32 = torch.from_numpy(np.load(f"{ASSETS}/clip32_tensor.npy")).cuda().float()
with torch.inference_mode():
    lo = vm(t32).cpu().numpy()
ref = np.load(f"{ASSETS}/ref_videomamba_logits.npy")
ok = np.allclose(lo, ref, rtol=1e-3, atol=1e-3) and lo.argmax() == ref.argmax()
gate("videomamba", ok, f"max|d|={np.abs(lo-ref).max():.2e} argmax {lo.argmax()}=={ref.argmax()}")

print("\nALL GATES PASS" if not failures else f"\nFAILED: {failures}")
sys.exit(1 if failures else 0)
